### ISSUE TITLE
Code is not running for training

### ISSUE THREAD

**Issue by VisheshTanwar-IITR** [danieljl/keras-image-captioning#3]
Hello @danieljl 

I am running the code but getting an error in "python -m keras_image_captioning.training   --training-label repro-final-model   --from-training-dir results/flickr8k/final-model" as

ValueError: Training label repro-final-model exits!

How to fix this bug?

Thanks

**Comment by danieljl** [comment]
Hi @VisheshTanwar-IITR

It means you have executed the training before. There are two options:
1. Find a directory named `repro-final-model` in `keras-image-captioning/var` directory and delete it; or
2. Choose another training label.
